import { ArrowDown, ArrowUpRight, Ellipsis, Sparkles } from 'lucide-react'
import { activities } from '../data/dashboard.js'

function SalesChart() {
  return <article className="panel sales-panel"><div className="panel-heading"><div><p className="eyebrow">REVENUE OVERVIEW</p><h2>Sales performance</h2></div><button className="select-button" type="button">Last 30 days <ArrowDown size={14} /></button></div><div className="chart-summary"><strong>$48,294<span>.80</span></strong><span className="chart-change"><ArrowUpRight size={14} /> 12.8%</span><span className="chart-summary-label">vs. last month</span></div><div className="chart-wrap" role="img" aria-label="Sales increased steadily over the last five weeks"><div className="chart-y-labels"><span>$15k</span><span>$10k</span><span>$5k</span><span>$0</span></div><svg className="sales-chart" viewBox="0 0 640 220" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="sales-fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#36a78c" stopOpacity=".2" /><stop offset="100%" stopColor="#36a78c" stopOpacity="0" /></linearGradient></defs><path className="chart-gridline" d="M0 25H640 M0 80H640 M0 135H640 M0 190H640" /><path className="chart-area" d="M0 177 C32 166 40 162 64 168 S107 155 128 151 S172 166 192 145 S232 129 256 138 S300 128 320 113 S364 125 384 104 S426 94 448 108 S490 85 512 91 S552 70 576 79 S615 56 640 48 L640 205 L0 205Z" /><path className="chart-line" d="M0 177 C32 166 40 162 64 168 S107 155 128 151 S172 166 192 145 S232 129 256 138 S300 128 320 113 S364 125 384 104 S426 94 448 108 S490 85 512 91 S552 70 576 79 S615 56 640 48" /><circle className="chart-point" cx="640" cy="48" r="5" /></svg><div className="chart-x-labels"><span>Sep 05</span><span>Sep 12</span><span>Sep 19</span><span>Sep 26</span><span>Oct 03</span></div></div><div className="chart-legend"><span><i /> This month</span><span className="legend-muted"><i /> Last month</span></div></article>
}

function ProfileCard() {
  return <article className="panel profile-panel"><div className="profile-panel-heading"><div><p className="eyebrow">YOUR ACCOUNT</p><h2>Store health</h2></div><button className="icon-button compact-button" aria-label="More store health options"><Ellipsis size={19} /></button></div><div className="health-score-row"><div className="health-ring"><div><strong>92</strong><span>/100</span></div></div><div className="health-copy"><strong>Looking good</strong><span>Your store is in great shape.</span></div></div><div className="health-progress"><span /></div><div className="health-footer"><span><Sparkles size={13} /> 3 quick wins</span><button type="button">View insights <ArrowUpRight size={13} /></button></div></article>
}

function ActivityFeed() {
  return <article className="panel activity-panel"><div className="panel-heading"><div><p className="eyebrow">LIVE UPDATES</p><h2>Recent activity</h2></div><button className="icon-button compact-button" aria-label="More activity options"><Ellipsis size={19} /></button></div><div className="activity-list">{activities.map((activity) => { const Icon = activity.icon; return <div className="activity-item" key={activity.title}><span className={`activity-icon ${activity.tone}`}><Icon size={15} strokeWidth={1.8} /></span><div className="activity-copy"><p>{activity.title}</p><span>{activity.detail}</span></div><time>{activity.time}</time></div> })}</div><button className="activity-link" type="button">View activity log <ArrowUpRight size={14} /></button></article>
}

function OrdersTable({ rows }) {
  return <div className="table-wrap"><table className="orders-table"><thead><tr><th>ORDER</th><th>CUSTOMER</th><th>PRODUCT</th><th>DATE</th><th>AMOUNT</th><th>STATUS</th><th aria-label="Actions" /></tr></thead><tbody>{rows.map((order) => <tr key={order.id}><td className="order-id">{order.id}</td><td><div className="customer-cell"><span className={`customer-avatar ${order.avatarTone}`}>{order.initials}</span><span>{order.customer}</span></div></td><td className="product-cell">{order.product}</td><td className="date-cell">{order.date}</td><td className="amount-cell">{order.amount}</td><td><span className={`status-pill ${order.statusTone}`}><i />{order.status}</span></td><td><button className="icon-button row-action" aria-label={`More options for ${order.id}`}><Ellipsis size={18} /></button></td></tr>)}{rows.length === 0 && <tr><td className="empty-state" colSpan="7">No orders match your search.</td></tr>}</tbody></table></div>
}

export default ActivityFeed
export { OrdersTable, ProfileCard, SalesChart }